------------------------------------------------
--        Monster Mash                        --
------------------------------------------------

MONSTER_MASH = { }

MONSTER_MASH.MONSTERS =
{
  gemturret =
  {
    id = 15000,
    r = 16,
    h = 40,
    prob = 30,
    health = 50,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  rapidfiretrooper =
  {
    id = 15001,
    r = 20,
    h = 56,
    prob = 30,
    health = 130,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  firewyvern =
  {
    id = 15002,
    r = 28,
    h = 50,
    prob = 30,
    health = 125,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  arachnid =
  {
    id = 15003,
    r = 15,
    h = 35,
    prob = 30,
    health = 50,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  quakegrunt =
  {
    id = 15004,
    r = 19,
    h = 52,
    prob = 30,
    health = 30,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  rocketturret =
  {
    id = 15005,
    r = 32,
    h = 32,
    prob = 30,
    health = 300,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  icegolem =
  {
    id = 15006,
    r = 22,
    h = 56,
    prob = 30,
    health = 360,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  icegolemspect =
  {
    id = 15007,
    r = 22,
    h = 56,
    prob = 30,
    health = 360,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  kullwarrior =
  {
    id = 15008,
    r = 20,
    h = 56,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  reaper =
  {
    id = 15009,
    r = 20,
    h = 56,
    prob = 30,
    health = 300,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  xenodemon =
  {
    id = 15010,
    r = 31,
    h = 56,
    prob = 30,
    health = 420,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  scimitar =
  {
    id = 15011,
    r = 16,
    h = 32,
    prob = 30,
    health = 50,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  demonwizard =
  {
    id = 15012,
    r = 22,
    h = 60,
    prob = 30,
    health = 220,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  skeletondemon =
  {
    id = 15013,
    r = 30,
    h = 56,
    prob = 30,
    health = 150,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  acolyte =
  {
    id = 15014,
    r = 20,
    h = 56,
    prob = 30,
    health = 150,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  skeletonimp =
  {
    id = 15015,
    r = 20,
    h = 56,
    prob = 30,
    health = 150,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  horneddemon =
  {
    id = 15016,
    r = 31,
    h = 56,
    prob = 30,
    health = 500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  disciple =
  {
    id = 15017,
    r = 20,
    h = 56,
    prob = 30,
    health = 300,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  rotwraith =
  {
    id = 15018,
    r = 20,
    h = 55,
    prob = 30,
    health = 150,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hellguard =
  {
    id = 15019,
    r = 24,
    h = 64,
    prob = 30,
    health = 300,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hellforgeddemon =
  {
    id = 15020,
    r = 30,
    h = 56,
    prob = 30,
    health = 150,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  invwar =
  {
    id = 15021,
    r = 30,
    h = 64,
    prob = 30,
    health = 640,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  blackwidow =
  {
    id = 15022,
    r = 64,
    h = 64,
    prob = 30,
    health = 500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  xenomorph =
  {
    id = 15023,
    r = 20,
    h = 56,
    prob = 30,
    health = 300,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  cultist =
  {
    id = 15024,
    r = 20,
    h = 56,
    prob = 30,
    health = 75,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hornbeast =
  {
    id = 15025,
    r = 20,
    h = 60,
    prob = 30,
    health = 500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  vore =
  {
    id = 15026,
    r = 48,
    h = 64,
    prob = 30,
    health = 900,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  d4caco =
  {
    id = 15027,
    r = 31,
    h = 56,
    prob = 30,
    health = 400,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  butcher =
  {
    id = 15028,
    r = 22,
    h = 62,
    prob = 30,
    health = 350,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  butcherspect =
  {
    id = 15029,
    r = 22,
    h = 62,
    prob = 30,
    health = 350,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  banshee =
  {
    id = 15030,
    r = 15,
    h = 60,
    prob = 30,
    health = 800,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  lostsoulhexencompatible =
  {
    id = 15031,
    r = 16,
    h = 56,
    prob = 30,
    health = 100,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  dalekbase =
  {
    id = 15032,
    r = 20,
    h = 56,
    prob = 30,
    health = 1250,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  dalek1 =
  {
    id = 15033,
    r = 20,
    h = 16,
    prob = 30,
    health = 1500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  dalek2 =
  {
    id = 15034,
    r = 20,
    h = 16,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  dalek3 =
  {
    id = 15035,
    r = 20,
    h = 16,
    prob = 30,
    health = 2500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  dalek4 =
  {
    id = 15036,
    r = 20,
    h = 16,
    prob = 30,
    health = 3000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  dalek5 =
  {
    id = 15037,
    r = 20,
    h = 16,
    prob = 30,
    health = 4000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  chaoswyvern =
  {
    id = 15038,
    r = 32,
    h = 65,
    prob = 30,
    health = 1000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  chaoscube =
  {
    id = 15039,
    r = 16,
    h = 32,
    prob = 30,
    health = 250,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  astrademon =
  {
    id = 15040,
    r = 31,
    h = 56,
    prob = 30,
    health = 400,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  crimsondisciple =
  {
    id = 15041,
    r = 16,
    h = 64,
    prob = 30,
    health = 175,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  crimsondisciplespect =
  {
    id = 15042,
    r = 16,
    h = 64,
    prob = 30,
    health = 175,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  infernal =
  {
    id = 15043,
    r = 32,
    h = 52,
    prob = 30,
    health = 420,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  nosferati =
  {
    id = 15044,
    r = 20,
    h = 64,
    prob = 30,
    health = 400,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  archerknight =
  {
    id = 15045,
    r = 20,
    h = 56,
    prob = 30,
    health = 355,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  zardaz =
  {
    id = 15046,
    r = 24,
    h = 72,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  testingmonster =
  {
    id = 15047,
    r = 20,
    h = 16,
    prob = 30,
    health = 10,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  aracknight =
  {
    id = 15048,
    r = 64,
    h = 64,
    prob = 30,
    health = 800,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  corpulent =
  {
    id = 15049,
    r = 48,
    h = 64,
    prob = 30,
    health = 600,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  impwarlord =
  {
    id = 15050,
    r = 20,
    h = 56,
    prob = 30,
    health = 180,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  dragonfamiliar =
  {
    id = 15051,
    r = 16,
    h = 32,
    prob = 30,
    health = 25,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  batfamiliar =
  {
    id = 15052,
    r = 12,
    h = 24,
    prob = 30,
    health = 10,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  cyclobus =
  {
    id = 15053,
    r = 48,
    h = 64,
    prob = 30,
    health = 600,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  bormereth =
  {
    id = 15054,
    r = 30,
    h = 64,
    prob = 30,
    health = 1200,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  apprenticeofdsparil =
  {
    id = 15055,
    r = 20,
    h = 56,
    prob = 30,
    health = 550,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  shotgunrobodude =
  {
    id = 15056,
    r = 20,
    h = 56,
    prob = 30,
    health = 200,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  slayerknight =
  {
    id = 15057,
    r = 20,
    h = 56,
    prob = 30,
    health = 600,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  blackopsmale =
  {
    id = 15058,
    r = 20,
    h = 56,
    prob = 30,
    health = 80,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  blackopsfemale =
  {
    id = 15059,
    r = 20,
    h = 56,
    prob = 30,
    health = 80,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  lordviletype1 =
  {
    id = 15060,
    r = 20,
    h = 60,
    prob = 30,
    health = 1500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  lordviletype2 =
  {
    id = 15061,
    r = 20,
    h = 60,
    prob = 30,
    health = 1250,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  lordviletype3 =
  {
    id = 15062,
    r = 20,
    h = 60,
    prob = 30,
    health = 1250,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  lordvileflyer =
  {
    id = 15063,
    r = 20,
    h = 60,
    prob = 30,
    health = 750,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  scorpionmastermind =
  {
    id = 15064,
    r = 96,
    h = 100,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hectebus =
  {
    id = 15065,
    r = 96,
    h = 112,
    prob = 30,
    health = 1000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  supercyber =
  {
    id = 15066,
    r = 40,
    h = 110,
    prob = 30,
    health = 4000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  insanityspider =
  {
    id = 15067,
    r = 96,
    h = 100,
    prob = 30,
    health = 5000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  erkkiboss =
  {
    id = 15068,
    r = 20,
    h = 16,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  erkkibossspawn =
  {
    id = 15069,
    r = 20,
    h = 16,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  aldhivas =
  {
    id = 15070,
    r = 22,
    h = 64,
    prob = 30,
    health = 2700,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  uberzombie =
  {
    id = 15071,
    r = 20,
    h = 56,
    prob = 30,
    health = 1800,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  evildoomguy =
  {
    id = 15072,
    r = 20,
    h = 56,
    prob = 30,
    health = 1900,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  deathknight =
  {
    id = 15073,
    r = 25,
    h = 75,
    prob = 30,
    health = 975,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hammerhound =
  {
    id = 15074,
    r = 48,
    h = 64,
    prob = 30,
    health = 3500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hhblastingcap =
  {
    id = 15075,
    r = 10,
    h = 6,
    prob = 30,
    health = 25,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hhorbitrockdummy =
  {
    id = 15076,
    r = 1,
    h = 1,
    prob = 30,
    health = 1000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hellsbattery =
  {
    id = 15077,
    r = 48,
    h = 128,
    prob = 30,
    health = 4000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  hellsbatterygore =
  {
    id = 15078,
    r = 48,
    h = 128,
    prob = 30,
    health = 500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  oldpentfxtail =
  {
    id = 15079,
    r = 20,
    h = 16,
    prob = 30,
    health = 1000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  pentfxtail =
  {
    id = 15080,
    r = 20,
    h = 16,
    prob = 30,
    health = 1000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  insanityarachnophyte =
  {
    id = 15081,
    r = 64,
    h = 100,
    prob = 30,
    health = 1250,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  reimually =
  {
    id = 15082,
    r = 20,
    h = 62,
    prob = 30,
    health = 4000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  marisaally =
  {
    id = 15083,
    r = 24,
    h = 64,
    prob = 30,
    health = 3500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  aliceally =
  {
    id = 15084,
    r = 24,
    h = 64,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  aliceallyspreaddoll =
  {
    id = 15085,
    r = 16,
    h = 48,
    prob = 30,
    health = 60,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  aliceallyringdoll =
  {
    id = 15086,
    r = 20,
    h = 16,
    prob = 30,
    health = 1000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  aliceallybeamdoll =
  {
    id = 15087,
    r = 20,
    h = 16,
    prob = 30,
    health = 1000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  aliceallychargedoll =
  {
    id = 15088,
    r = 20,
    h = 16,
    prob = 30,
    health = 30,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  tenshially =
  {
    id = 15089,
    r = 24,
    h = 64,
    prob = 30,
    health = 2500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  ikually =
  {
    id = 15090,
    r = 24,
    h = 64,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  sanaeally =
  {
    id = 15091,
    r = 24,
    h = 64,
    prob = 30,
    health = 3000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  suikaally =
  {
    id = 15092,
    r = 24,
    h = 64,
    prob = 30,
    health = 2500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  yuyukoally =
  {
    id = 15093,
    r = 24,
    h = 64,
    prob = 30,
    health = 2500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  youmually =
  {
    id = 15094,
    r = 24,
    h = 64,
    prob = 30,
    health = 3000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  remiliaally =
  {
    id = 15095,
    r = 24,
    h = 64,
    prob = 30,
    health = 3000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  sakuyaally =
  {
    id = 15096,
    r = 24,
    h = 64,
    prob = 30,
    health = 2500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  patchoulially =
  {
    id = 15097,
    r = 24,
    h = 64,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  cirnoally =
  {
    id = 15098,
    r = 24,
    h = 64,
    prob = 30,
    health = 2187,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  komachially =
  {
    id = 15099,
    r = 24,
    h = 64,
    prob = 30,
    health = 2000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  meilingally =
  {
    id = 15100,
    r = 24,
    h = 64,
    prob = 30,
    health = 2500,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
  utsuhoally =
  {
    id = 15101,
    r = 32,
    h = 64,
    prob = 30,
    health = 3000,
    damage = 10,
    attack = "missile",
    density = 0.9
  },
}
OB_MODULES["monster_mash"] =
{
  name = "monster_mash_control",
  label = _("Monster Mash"),
  game = "doomish",
  port = "zdoom",
  tables =
  {
    MONSTER_MASH
  },
  hooks =
  {
    setup = MONSTER_MASH.control_setup
  },
  options =
  {
    {
      name = "float_gemturret",
      label = _("GemTurret"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of GemTurret"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_rapidfiretrooper",
      label = _("RapidFireTrooper"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of RapidFireTrooper"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_firewyvern",
      label = _("FireWyvern"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of FireWyvern"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_arachnid",
      label = _("Arachnid"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Arachnid"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_quakegrunt",
      label = _("QuakeGrunt"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of QuakeGrunt"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_rocketturret",
      label = _("RocketTurret"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of RocketTurret"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_icegolem",
      label = _("IceGolem"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of IceGolem"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_icegolemspect",
      label = _("IceGolemSpect"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of IceGolemSpect"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_kullwarrior",
      label = _("kullwarrior"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of kullwarrior"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_reaper",
      label = _("Reaper"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Reaper"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_xenodemon",
      label = _("Xenodemon"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Xenodemon"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_scimitar",
      label = _("Scimitar"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Scimitar"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_demonwizard",
      label = _("DemonWizard"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of DemonWizard"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_skeletondemon",
      label = _("SkeletonDemon"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of SkeletonDemon"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_acolyte",
      label = _("Acolyte"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Acolyte"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_skeletonimp",
      label = _("SkeletonImp"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of SkeletonImp"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_horneddemon",
      label = _("HornedDemon"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HornedDemon"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_disciple",
      label = _("Disciple"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Disciple"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_rotwraith",
      label = _("RotWraith"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of RotWraith"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hellguard",
      label = _("HellGuard"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HellGuard"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hellforgeddemon",
      label = _("HellforgedDemon"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HellforgedDemon"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_invwar",
      label = _("invwar"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of invwar"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_blackwidow",
      label = _("BlackWidow"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of BlackWidow"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_xenomorph",
      label = _("Xenomorph"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Xenomorph"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_cultist",
      label = _("Cultist"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Cultist"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hornbeast",
      label = _("HornBeast"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HornBeast"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_vore",
      label = _("Vore"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Vore"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_d4caco",
      label = _("D4Caco"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of D4Caco"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_butcher",
      label = _("Butcher"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Butcher"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_butcherspect",
      label = _("ButcherSpect"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ButcherSpect"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_banshee",
      label = _("Banshee"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Banshee"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_lostsoulhexencompatible",
      label = _("LostSoulHexenCompatible"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of LostSoulHexenCompatible"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_dalekbase",
      label = _("DalekBase"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of DalekBase"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_dalek1",
      label = _("Dalek1"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Dalek1"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_dalek2",
      label = _("Dalek2"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Dalek2"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_dalek3",
      label = _("Dalek3"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Dalek3"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_dalek4",
      label = _("Dalek4"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Dalek4"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_dalek5",
      label = _("Dalek5"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Dalek5"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_chaoswyvern",
      label = _("ChaosWyvern"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ChaosWyvern"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_chaoscube",
      label = _("ChaosCube"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ChaosCube"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_astrademon",
      label = _("Astrademon"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Astrademon"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_crimsondisciple",
      label = _("CrimsonDisciple"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of CrimsonDisciple"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_crimsondisciplespect",
      label = _("CrimsonDiscipleSpect"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of CrimsonDiscipleSpect"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_infernal",
      label = _("Infernal"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Infernal"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_nosferati",
      label = _("Nosferati"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Nosferati"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_archerknight",
      label = _("ArcherKnight"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ArcherKnight"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_zardaz",
      label = _("zardaz"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of zardaz"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_testingmonster",
      label = _("testingmonster"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of testingmonster"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_aracknight",
      label = _("Aracknight"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Aracknight"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_corpulent",
      label = _("Corpulent"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Corpulent"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_impwarlord",
      label = _("ImpWarlord"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ImpWarlord"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_dragonfamiliar",
      label = _("DragonFamiliar"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of DragonFamiliar"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_batfamiliar",
      label = _("BatFamiliar"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of BatFamiliar"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_cyclobus",
      label = _("Cyclobus"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Cyclobus"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_bormereth",
      label = _("Bormereth"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Bormereth"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_apprenticeofdsparil",
      label = _("ApprenticeofDsparil"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ApprenticeofDsparil"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_shotgunrobodude",
      label = _("ShotgunRobodude"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ShotgunRobodude"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_slayerknight",
      label = _("SlayerKnight"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of SlayerKnight"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_blackopsmale",
      label = _("BlackOpsMale"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of BlackOpsMale"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_blackopsfemale",
      label = _("BlackOpsFemale"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of BlackOpsFemale"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_lordviletype1",
      label = _("LordVileType1"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of LordVileType1"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_lordviletype2",
      label = _("LordVileType2"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of LordVileType2"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_lordviletype3",
      label = _("LordVileType3"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of LordVileType3"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_lordvileflyer",
      label = _("LordVileFlyer"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of LordVileFlyer"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_scorpionmastermind",
      label = _("ScorpionMastermind"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ScorpionMastermind"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hectebus",
      label = _("Hectebus"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Hectebus"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_supercyber",
      label = _("SuperCyber"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of SuperCyber"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_insanityspider",
      label = _("InsanitySpider"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of InsanitySpider"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_erkkiboss",
      label = _("ErkkiBoss"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ErkkiBoss"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_erkkibossspawn",
      label = _("ErkkiBossSpawn"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ErkkiBossSpawn"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_aldhivas",
      label = _("Aldhivas"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Aldhivas"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_uberzombie",
      label = _("Uberzombie"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Uberzombie"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_evildoomguy",
      label = _("EvilDoomguy"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of EvilDoomguy"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_deathknight",
      label = _("Deathknight"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of Deathknight"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hammerhound",
      label = _("HammerHound"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HammerHound"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hhblastingcap",
      label = _("HHBlastingCap"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HHBlastingCap"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hhorbitrockdummy",
      label = _("HHOrbitRockDummy"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HHOrbitRockDummy"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hellsbattery",
      label = _("HellsBattery"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HellsBattery"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_hellsbatterygore",
      label = _("HellsBatteryGore"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of HellsBatteryGore"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_oldpentfxtail",
      label = _("OldPentFXTail"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of OldPentFXTail"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_pentfxtail",
      label = _("PentFXTail"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of PentFXTail"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_insanityarachnophyte",
      label = _("InsanityArachnophyte"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of InsanityArachnophyte"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_reimually",
      label = _("ReimuAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of ReimuAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_marisaally",
      label = _("MarisaAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of MarisaAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_aliceally",
      label = _("AliceAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of AliceAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_aliceallyspreaddoll",
      label = _("AliceAllySpreadDoll"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of AliceAllySpreadDoll"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_aliceallyringdoll",
      label = _("AliceAllyRingDoll"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of AliceAllyRingDoll"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_aliceallybeamdoll",
      label = _("AliceAllyBeamDoll"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of AliceAllyBeamDoll"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_aliceallychargedoll",
      label = _("AliceAllyChargeDoll"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of AliceAllyChargeDoll"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_tenshially",
      label = _("TenshiAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of TenshiAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_ikually",
      label = _("IkuAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of IkuAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_sanaeally",
      label = _("SanaeAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of SanaeAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_suikaally",
      label = _("SuikaAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of SuikaAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_yuyukoally",
      label = _("YuyukoAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of YuyukoAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_youmually",
      label = _("YoumuAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of YoumuAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_remiliaally",
      label = _("RemiliaAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of RemiliaAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_sakuyaally",
      label = _("SakuyaAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of SakuyaAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_patchoulially",
      label = _("PatchouliAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of PatchouliAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_cirnoally",
      label = _("CirnoAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of CirnoAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_komachially",
      label = _("KomachiAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of KomachiAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_meilingally",
      label = _("MeilingAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of MeilingAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
    {
      name = "float_utsuhoally",
      label = _("UtsuhoAlly"),
      valuator = "slider",
      min = 0,
      max = 20,
      increment = .02,
      default = _("Default"),
      nan = _("Default"),
      tooltip = _("Control the amount of UtsuhoAlly"),
      presets = _("0:0 (None at all,.02:0.02 (Scarce),.14:0.14 (Less),.5:0.5 (Plenty),1.2:1.2 (More),3:3 (Heaps),20:20 (INSANE)"),
      randomize_group = "monsters",
    },
  },
}
