###############################################################################
# source_report.cr — Per-WAD/PK3 contents report
#
# Generates a report showing which monsters, weapons, ammo, and pickups
# came from each source WAD/PK3. Highlights sources with no usable content.
###############################################################################

def generate_source_report(actordb : Array(Actor),
                           weapon_actor_set : Set(String),
                           ammo_actor_set : Set(String),
                           pickup_actor_set : Set(String))

  log(2, "Generating source mod contents report...")

  # Get list of all included WADs from Processing/ directory.
  # This includes both standalone mods and promoted nested WADs (Parent__Child).
  all_source_names = Dir.children(PROCESSING_DIR)
    .select { |f| Dir.exists?("#{PROCESSING_DIR}/#{f}") }
    .sort_by(&.downcase)

  # Build per-WAD lists of classified actors (excluding built-in actors)
  wad_monsters = Hash(String, Array(String)).new
  wad_weapons  = Hash(String, Array(String)).new
  wad_ammo     = Hash(String, Array(String)).new
  wad_pickups  = Hash(String, Array(String)).new
  wad_allies   = Hash(String, Array(String)).new

  actordb.each do |actor|
    next if actor.built_in
    wad = actor.source_wad_folder
    next if wad == "UNDEFINED"

    name = actor.name_with_case
    name_lc = actor.name.downcase

    # Categorize actor
    if weapon_actor_set.includes?(name_lc)
      wad_weapons[wad] ||= Array(String).new
      wad_weapons[wad] << name
    elsif ammo_actor_set.includes?(name_lc)
      wad_ammo[wad] ||= Array(String).new
      wad_ammo[wad] << name
    elsif pickup_actor_set.includes?(name_lc)
      wad_pickups[wad] ||= Array(String).new
      wad_pickups[wad] << name
    elsif (actor.monster || actor.ismonster) && actor.friendly
      wad_allies[wad] ||= Array(String).new
      wad_allies[wad] << name
    elsif actor.monster || actor.ismonster
      wad_monsters[wad] ||= Array(String).new
      wad_monsters[wad] << name
    end
  end

  # Identify source WADs with no classified content
  wads_with_content = Set(String).new
  [wad_monsters, wad_weapons, wad_ammo, wad_pickups, wad_allies].each do |category|
    category.each_key { |wad| wads_with_content.add(wad) }
  end

  # Identify source WADs with no classified content
  empty_wads = all_source_names.reject { |name| wads_with_content.includes?(name) }

  # Write report
  report_path = "#{COMPLETED_DIR}/source_contents_report.txt"
  log(2, "Writing source contents report to: #{report_path}")

  File.open(report_path, "w") do |f|
    f.puts "Monster Mash — Source Mod Contents Report"
    f.puts "Generated by Unwad V2"
    f.puts "=" * 60
    f.puts ""

    ###########################################################################
    # Section: WADs with no usable content
    ###########################################################################
    unless empty_wads.empty?
      f.puts "!" * 60
      f.puts "WARNING: Sources with NO monsters, weapons, ammo, or pickups:"
      f.puts "!" * 60
      empty_wads.each do |name|
        f.puts "  *** #{name} ***"
      end
      f.puts ""
      f.puts "(These WADs/PK3s may contain only decorations, textures, sounds,"
      f.puts " or other non-actor resources. Or their actors may have been"
      f.puts " filtered out by classification rules.)"
      f.puts ""
    end

    ###########################################################################
    # Section: Per-WAD breakdown
    ###########################################################################

    f.puts "-" * 60
    f.puts "PER-SOURCE BREAKDOWN"
    f.puts "-" * 60
    f.puts ""

    all_source_names.each do |wad_name|
      monsters = wad_monsters[wad_name]? || Array(String).new
      weapons  = wad_weapons[wad_name]? || Array(String).new
      ammo     = wad_ammo[wad_name]? || Array(String).new
      pickups  = wad_pickups[wad_name]? || Array(String).new
      allies   = wad_allies[wad_name]? || Array(String).new

      total = monsters.size + weapons.size + ammo.size + pickups.size + allies.size

      if total == 0
        f.puts "#{wad_name}  (NO CONTENT)"
        f.puts ""
        next
      end

      f.puts "#{wad_name}  (#{total} actors)"

      unless monsters.empty?
        f.puts "  Monsters (#{monsters.size}):"
        monsters.sort_by(&.downcase).each { |name| f.puts "    #{name}" }
      end

      unless allies.empty?
        f.puts "  Allies (#{allies.size}):"
        allies.sort_by(&.downcase).each { |name| f.puts "    #{name}" }
      end

      unless weapons.empty?
        f.puts "  Weapons (#{weapons.size}):"
        weapons.sort_by(&.downcase).each { |name| f.puts "    #{name}" }
      end

      unless ammo.empty?
        f.puts "  Ammo (#{ammo.size}):"
        ammo.sort_by(&.downcase).each { |name| f.puts "    #{name}" }
      end

      unless pickups.empty?
        f.puts "  Pickups (#{pickups.size}):"
        pickups.sort_by(&.downcase).each { |name| f.puts "    #{name}" }
      end

      f.puts ""
    end

    ###########################################################################
    # Section: Summary totals
    ###########################################################################

    f.puts "-" * 60
    f.puts "SUMMARY"
    f.puts "-" * 60

    total_monsters = wad_monsters.values.sum(&.size)
    total_weapons  = wad_weapons.values.sum(&.size)
    total_ammo     = wad_ammo.values.sum(&.size)
    total_pickups  = wad_pickups.values.sum(&.size)
    total_allies   = wad_allies.values.sum(&.size)

    f.puts "  Source WADs/PK3s:  #{all_source_names.size}"
    f.puts "  With content:      #{wads_with_content.size}"
    f.puts "  Without content:   #{empty_wads.size}"
    f.puts ""
    f.puts "  Total monsters:    #{total_monsters}"
    f.puts "  Total allies:      #{total_allies}"
    f.puts "  Total weapons:     #{total_weapons}"
    f.puts "  Total ammo:        #{total_ammo}"
    f.puts "  Total pickups:     #{total_pickups}"
    f.puts ""
  end

  log(2, "Source contents report written: #{report_path}")

  # Also print a console summary
  puts ""
  puts "=== Source Mod Contents ==="
  puts "  #{wads_with_content.size}/#{all_source_names.size} sources have classified actors"
  unless empty_wads.empty?
    puts "  #{empty_wads.size} source(s) with NO content: #{empty_wads.join(", ")}"
  end
  puts "  See #{report_path} for full details."
  puts ""
end
